name: Lint
on:
  pull_request:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'revive.toml'
      - '.github/workflows/revive.yaml'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Install revive
        run: go install github.com/mgechev/revive@latest
      - name: Run revive
        run: |
          revive -config revive.toml -formatter friendly ./...
